defaults:
  - _self_

debug: false
seed: 0

num_steps: 100000
env: CartPole-v0
gromov_wasserstein: false

hydra:
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}